services:
  db:
    image: postgres:14.15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: ../backend/
    image: djangoproduct:latest
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - redoc:/app/api/docs/
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
    name: postgres_data
  static_value:
  redoc:
