services:
  db:
    image: postgres:14.15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: ../backend/
    image: djangoproduct:latest
    container_name: backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
    name: postgres_data